[package]
name = "etherweasel_rs"
version = "0.1.0"
edition = "2021"

# This target is required as a dummy target to allow cargo to cache dependencies
# during build. See https://stackoverflow.com/a/39662015/3888444   
[lib]
name = "cache"
path = "cache.rs"

[dependencies]
af_packet = "0.3.1"
dns-parser = "0.8.0"
pktparse = "0.7.1"
nom = "7.1.1"
# Tokio
tokio = { version = "1", features = ["full"] }
axum = "0.5.16"
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
# Extras
socket2 = "0.4.7"
bytes = "1"

